version: '3.7'  # Corregido desde '0.7', ya que 3.7 es una versión más estándar.
services:
  db:
    build: ./db
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db-network
    expose:
      - "5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
    networks:
      - db-network
      - backend-network
    depends_on:
      - db

  streamlit:
    build: ./api
    environment:
      ENDPOINT_URL: "http://backend:8000/"  # URL interna para acceder al backend
    networks:
      - backend-network
    depends_on:
      - backend
    ports:
      - "80:8501"  # Accesible en el host a través del puerto 80

networks:
  db-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  data-volume:




docker build -t db .
docker run --name f0801eb0ae729b937f76f45582473f170a4c79cf961cd35e50ab9fc423eaaaed -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=123 -e POSTGRES_DB=challenge -p 5432:5432 -d db_image

docker run --name c3ad517d1169c83adac440c6e5f4b511fc15a25465bb539110a99347a6a397ca -e USER=postgres -e PASSWORD=123 -e HOST=localhost -e NAME=challenge -p 8000:8000 -d backend_image


docker exec -it 8f6fb2099387117ffb294ba402bf378500fec81fd49570588a1ac1246f0ba70b /bin/bash

psql -U postgres-d challenge -h localhost -p 5432


